---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: backups.configuration.artifactory.jfrog.m.crossplane.io
spec:
  group: configuration.artifactory.jfrog.m.crossplane.io
  names:
    categories:
    - crossplane
    - managed
    - artifactory
    kind: Backup
    listKind: BackupList
    plural: backups
    singular: backup
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Synced')].status
      name: SYNCED
      type: string
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
    - jsonPath: .metadata.annotations.crossplane\.io/external-name
      name: EXTERNAL-NAME
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Backup is the Schema for the Backups API. This resource can be
          used to manage the automatic and periodic backups of the entire Artifactory
          instance. When an artifactory_backup resource is configured and enabled
          to true, backup of the entire Artifactory system will be done automatically
          and periodically. The backup process creates a time-stamped directory in
          the target backup directory. See JFrog Artifactory Backup https://www.jfrog.com/confluence/display/JFROG/Backups
          for more details. ~>Only supported in self-hosted environment.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: BackupSpec defines the desired state of Backup
            properties:
              forProvider:
                properties:
                  createArchive:
                    description: |-
                      (Boolean) If set to true, backups will be created within a Zip archive (Slow and CPU intensive). Default value is false
                      If set to true, backups will be created within a Zip archive (Slow and CPU intensive). Default value is `false`
                    type: boolean
                  cronExp:
                    description: |-
                      (String) Cron expression to control the backup frequency.
                      Cron expression to control the backup frequency.
                    type: string
                  enabled:
                    description: |-
                      (Boolean) Flag to enable or disable the backup config. Default value is true.
                      Flag to enable or disable the backup config. Default value is `true`.
                    type: boolean
                  excludeNewRepositories:
                    description: |-
                      (Boolean) When set to true, new repositories will not be automatically added to the backup. Default value is false.
                      When set to true, new repositories will not be automatically added to the backup. Default value is `false`.
                    type: boolean
                  excludedRepositories:
                    description: |-
                      (List of String) List of excluded repositories from the backup.
                      List of excluded repositories from the backup.
                    items:
                      type: string
                    type: array
                  exportMissionControl:
                    description: |-
                      (Boolean) When set to true, mission control will not be automatically added to the backup. Default value is false.
                      When set to true, mission control will not be automatically added to the backup. Default value is `false`.
                    type: boolean
                  retentionPeriodHours:
                    description: |-
                      incremental backups. Default value is 168 hours i.e. 7 days.
                      The number of hours to keep a backup before Artifactory will clean it up to free up disk space. Applicable only to non-incremental backups. Default value is 168 hours i.e. 7 days.
                    type: number
                  sendMailOnError:
                    description: |-
                      (Boolean) If set to true, all Artifactory administrators will be notified by email if any problem is encountered during backup. Default value is true.
                      If set to true, all Artifactory administrators will be notified by email if any problem is encountered during backup. Default value is `true`.
                    type: boolean
                  verifyDiskSpace:
                    description: |-
                      incremental backups. Default value is false.
                      If set, Artifactory will verify that the backup target location has enough disk space available to hold the backed up data. If there is not enough space available, Artifactory will abort the backup and write a message in the log file. Applicable only to non-incremental backups. Default value is `false`.
                    type: boolean
                type: object
              initProvider:
                description: |-
                  THIS IS A BETA FIELD. It will be honored
                  unless the Management Policies feature flag is disabled.
                  InitProvider holds the same fields as ForProvider, with the exception
                  of Identifier and other resource reference fields. The fields that are
                  in InitProvider are merged into ForProvider when the resource is created.
                  The same fields are also added to the terraform ignore_changes hook, to
                  avoid updating them after creation. This is useful for fields that are
                  required on creation, but we do not desire to update them after creation,
                  for example because of an external controller is managing them, like an
                  autoscaler.
                properties:
                  createArchive:
                    description: |-
                      (Boolean) If set to true, backups will be created within a Zip archive (Slow and CPU intensive). Default value is false
                      If set to true, backups will be created within a Zip archive (Slow and CPU intensive). Default value is `false`
                    type: boolean
                  cronExp:
                    description: |-
                      (String) Cron expression to control the backup frequency.
                      Cron expression to control the backup frequency.
                    type: string
                  enabled:
                    description: |-
                      (Boolean) Flag to enable or disable the backup config. Default value is true.
                      Flag to enable or disable the backup config. Default value is `true`.
                    type: boolean
                  excludeNewRepositories:
                    description: |-
                      (Boolean) When set to true, new repositories will not be automatically added to the backup. Default value is false.
                      When set to true, new repositories will not be automatically added to the backup. Default value is `false`.
                    type: boolean
                  excludedRepositories:
                    description: |-
                      (List of String) List of excluded repositories from the backup.
                      List of excluded repositories from the backup.
                    items:
                      type: string
                    type: array
                  exportMissionControl:
                    description: |-
                      (Boolean) When set to true, mission control will not be automatically added to the backup. Default value is false.
                      When set to true, mission control will not be automatically added to the backup. Default value is `false`.
                    type: boolean
                  retentionPeriodHours:
                    description: |-
                      incremental backups. Default value is 168 hours i.e. 7 days.
                      The number of hours to keep a backup before Artifactory will clean it up to free up disk space. Applicable only to non-incremental backups. Default value is 168 hours i.e. 7 days.
                    type: number
                  sendMailOnError:
                    description: |-
                      (Boolean) If set to true, all Artifactory administrators will be notified by email if any problem is encountered during backup. Default value is true.
                      If set to true, all Artifactory administrators will be notified by email if any problem is encountered during backup. Default value is `true`.
                    type: boolean
                  verifyDiskSpace:
                    description: |-
                      incremental backups. Default value is false.
                      If set, Artifactory will verify that the backup target location has enough disk space available to hold the backed up data. If there is not enough space available, Artifactory will abort the backup and write a message in the log file. Applicable only to non-incremental backups. Default value is `false`.
                    type: boolean
                type: object
              managementPolicies:
                default:
                - '*'
                description: |-
                  THIS IS A BETA FIELD. It is on by default but can be opted out
                  through a Crossplane feature flag.
                  ManagementPolicies specify the array of actions Crossplane is allowed to
                  take on the managed and external resources.
                  See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
                  and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
                items:
                  description: |-
                    A ManagementAction represents an action that the Crossplane controllers
                    can take on an external resource.
                  enum:
                  - Observe
                  - Create
                  - Update
                  - Delete
                  - LateInitialize
                  - '*'
                  type: string
                type: array
              providerConfigRef:
                default:
                  kind: ClusterProviderConfig
                  name: default
                description: |-
                  ProviderConfigReference specifies how the provider that will be used to
                  create, observe, update, and delete this managed resource should be
                  configured.
                properties:
                  kind:
                    description: Kind of the referenced object.
                    type: string
                  name:
                    description: Name of the referenced object.
                    type: string
                required:
                - kind
                - name
                type: object
              writeConnectionSecretToRef:
                description: |-
                  WriteConnectionSecretToReference specifies the namespace and name of a
                  Secret to which any connection details for this managed resource should
                  be written. Connection details frequently include the endpoint, username,
                  and password required to connect to the managed resource.
                properties:
                  name:
                    description: Name of the secret.
                    type: string
                required:
                - name
                type: object
            required:
            - forProvider
            type: object
            x-kubernetes-validations:
            - message: spec.forProvider.cronExp is a required parameter
              rule: '!(''*'' in self.managementPolicies || ''Create'' in self.managementPolicies
                || ''Update'' in self.managementPolicies) || has(self.forProvider.cronExp)
                || (has(self.initProvider) && has(self.initProvider.cronExp))'
          status:
            description: BackupStatus defines the observed state of Backup.
            properties:
              atProvider:
                properties:
                  createArchive:
                    description: |-
                      (Boolean) If set to true, backups will be created within a Zip archive (Slow and CPU intensive). Default value is false
                      If set to true, backups will be created within a Zip archive (Slow and CPU intensive). Default value is `false`
                    type: boolean
                  cronExp:
                    description: |-
                      (String) Cron expression to control the backup frequency.
                      Cron expression to control the backup frequency.
                    type: string
                  enabled:
                    description: |-
                      (Boolean) Flag to enable or disable the backup config. Default value is true.
                      Flag to enable or disable the backup config. Default value is `true`.
                    type: boolean
                  excludeNewRepositories:
                    description: |-
                      (Boolean) When set to true, new repositories will not be automatically added to the backup. Default value is false.
                      When set to true, new repositories will not be automatically added to the backup. Default value is `false`.
                    type: boolean
                  excludedRepositories:
                    description: |-
                      (List of String) List of excluded repositories from the backup.
                      List of excluded repositories from the backup.
                    items:
                      type: string
                    type: array
                  exportMissionControl:
                    description: |-
                      (Boolean) When set to true, mission control will not be automatically added to the backup. Default value is false.
                      When set to true, mission control will not be automatically added to the backup. Default value is `false`.
                    type: boolean
                  id:
                    type: string
                  retentionPeriodHours:
                    description: |-
                      incremental backups. Default value is 168 hours i.e. 7 days.
                      The number of hours to keep a backup before Artifactory will clean it up to free up disk space. Applicable only to non-incremental backups. Default value is 168 hours i.e. 7 days.
                    type: number
                  sendMailOnError:
                    description: |-
                      (Boolean) If set to true, all Artifactory administrators will be notified by email if any problem is encountered during backup. Default value is true.
                      If set to true, all Artifactory administrators will be notified by email if any problem is encountered during backup. Default value is `true`.
                    type: boolean
                  verifyDiskSpace:
                    description: |-
                      incremental backups. Default value is false.
                      If set, Artifactory will verify that the backup target location has enough disk space available to hold the backed up data. If there is not enough space available, Artifactory will abort the backup and write a message in the log file. Applicable only to non-incremental backups. Default value is `false`.
                    type: boolean
                type: object
              conditions:
                description: Conditions of the resource.
                items:
                  description: A Condition that may apply to a resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        LastTransitionTime is the last time this condition transitioned from one
                        status to another.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        A Message containing details about this condition's last transition from
                        one status to another, if any.
                      type: string
                    observedGeneration:
                      description: |-
                        ObservedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: A Reason for this condition's last transition from
                        one status to another.
                      type: string
                    status:
                      description: Status of this condition; is it currently True,
                        False, or Unknown?
                      type: string
                    type:
                      description: |-
                        Type of this condition. At most one of each condition type may apply to
                        a resource at any point in time.
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              observedGeneration:
                description: |-
                  ObservedGeneration is the latest metadata.generation
                  which resulted in either a ready state, or stalled due to error
                  it can not recover from without human intervention.
                format: int64
                type: integer
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
